### ISSUE TITLE
Diversity estimates not plausible

### ISSUE THREAD

**Issue by ARetter90** [mooreryan/divnet-rs#9] opened 2022-07-06 09:08 UTC
Hi,

When computing Shannon and Inverse Simpson diversities for my samples from the divnet-rs output, samples that have a very low observed richness have shannon diversities of 9 and higher - how can this be? This is biologically not logical if i only have say 5 species in  that sample and such a high shannon index and inverse simspn numbers of >1000. Do you have any suggestion on how to deal with this?

Alice

**Comment by mooreryan** [comment] 2022-07-06 15:58
Hi Alice, thanks for your report. 

It's hard for me to say what's going on without seeing how you ran all the commands and your input data. 

Would you be able to share your input data, the exact command line command you ran, and the R code in which you calculated the diversity measures? If so I can try to reproduce the issue. 

Thanks!

**Comment by mooreryan** [comment] 2022-07-06 18:06
I see that some members of the Willis lab have responded to this issue on the DivNet R page (https://github.com/adw96/DivNet/issues/126).

I'm closing the issue here to avoid duplicated work between the two groups.

Feel free to reopen if it turns out to be an issue specific to divnet-rs, and not the DivNet method in general.

**Closed as completed by mooreryan** 2022-07-06 18:06 UTC
